CREATE TABLE IF NOT EXISTS donations (
    id SERIAL PRIMARY KEY,
    userId INTEGER NOT NULL,
    campaignId INTEGER NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY (userId) REFERENCES users (id)
);
