version: '3.8'

services:
  db:
    image: postgres:15-alpine # Use a lightweight PostgreSQL image
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: donation_platform
    ports:
      - "5432:5432" # Expose PostgreSQL on port 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # Mount a local directory for data persistence

volumes:
  db_data:
    driver: local
