version: '3.8'

services:
  db:
    image: postgres:15-alpine # Use a lightweight PostgreSQL image
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: donation_platform
    ports:
      - "5432:5432" # Expose PostgreSQL on port 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # Mount a local directory for data persistence

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite_container
    ports:
      - "10000:10000" # Blob service
      - "10001:10001" # Queue service
      - "10002:10002" # Table service
    volumes:
      - ./azurite-data:/data # Persistent storage for Azurite
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"


volumes:
  db_data:
    driver: local
  azurite_data:
    driver: local
